language: python
python:
  - '3.6'
  - '3.7'
branches:
  only:
  - release
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
install:
  - python setup.py install
script:
  - python setup.py pytest